export interface StepDefinition {
  number: number;
  name: string;
  month: number;
  monthLabel: string;
  hours: number;
  theory: string;
  mainExercise: string;
  outputs: string[];
  mentors: string[];
  knaasCompanion: string;
  knaasAnalyst?: string;
  knaasGenerator?: string;
  saber: string;
  decidir: string;
  hacer: string;
}

export const ACTIVA_STEPS: StepDefinition[] = [
  {
    number: 1,
    name: "Diagnóstico 360°",
    month: 1,
    monthLabel: "Diagnóstico, autoconocimiento y claridad estratégica",
    hours: 6,
    theory: "Qué KPIs importan y por qué. Los 6 errores conceptuales. Las 7 áreas de madurez empresarial.",
    mainExercise: "Test de madurez empresarial conversacional + volcado de datos en PodiumMetrics con detección de errores en tiempo real.",
    outputs: ["Mapa de madurez empresarial", "Informe diagnóstico 360° cuantitativo y cualitativo", "Tabla de KPIs de partida"],
    mentors: ["Alex Vallés"],
    knaasCompanion: "Conduce el test de madurez en 7 áreas, guía el volcado de datos, detecta los 6 errores conceptuales, genera el informe 360° y guarda el snapshot protegido.",
    saber: "Comprende qué mide cada KPI y puede explicar los 6 errores conceptuales aplicados a su clínica.",
    decidir: "Ha identificado los 3 puntos más débiles de su clínica y las prioridades de trabajo del programa.",
    hacer: "Tiene el informe 360° completo (cuanti + cuali) y la tabla de KPIs de partida como snapshot protegido en PodiumMetrics.",
  },
  {
    number: 2,
    name: "Mentalidad, liderazgo e introspección",
    month: 1,
    monthLabel: "Diagnóstico, autoconocimiento y claridad estratégica",
    hours: 8,
    theory: "Cambio de identidad fisio→empresario. Responsabilidad 100%. 6 estilos de liderazgo Goleman. Motores vs frenos. El Pacto de Ulises.",
    mainExercise: "Definición personal de éxito con métricas y fechas. Autoevaluación de 6 estilos. Análisis profundo motores vs frenos. Plan de desarrollo como líder.",
    outputs: ["Perfil empresarial personal", "Mapa de liderazgo personal", "Plan de desarrollo como líder y dueño", "Pacto de Ulises"],
    mentors: ["Alex Vallés", "Luis Ezcurra"],
    knaasCompanion: "Conduce el análisis en profundidad de motores y frenos, construye el plan de desarrollo con objetivos y fechas, ayuda a formular el Pacto de Ulises.",
    knaasAnalyst: "Devil's Advocate sobre creencias limitantes — ¿son realmente creencias o restricciones reales del mercado?",
    saber: "Puede articular su definición de éxito con números y fecha, y nombrar sus 3 frenos principales con su impacto concreto.",
    decidir: "Ha decidido los 3 comportamientos de liderazgo que trabajará durante el programa con acciones específicas.",
    hacer: "Tiene el perfil empresarial, el mapa de liderazgo, el plan de desarrollo y el Pacto de Ulises redactado en sus palabras.",
  },
  {
    number: 3,
    name: "Fundamentos, modelos y visión estratégica",
    month: 1,
    monthLabel: "Diagnóstico, autoconocimiento y claridad estratégica",
    hours: 7,
    theory: "Los 4 modelos de clínica. Ciclo del negocio. Competitividad en fisioterapia. Propósito como criterio de decisión.",
    mainExercise: "Identificación del modelo actual y objetivo. Ejercicio del puzzle del propósito. Construcción de la visión con KPIs concretos.",
    outputs: ["Declaración de propósito", "Ficha de modelo y fase de ciclo", "Documento de visión con KPIs objetivo"],
    mentors: ["Alex Vallés"],
    knaasCompanion: "Identifica modelo y fase del ciclo a partir de los datos del P1. Guía el ejercicio del propósito.",
    knaasGenerator: "Borrador de la declaración de propósito y el documento de visión con KPIs objetivo.",
    saber: "Puede explicar su modelo actual, el objetivo, y por qué ese modelo es coherente con su diagnóstico.",
    decidir: "Ha elegido modelo objetivo con argumentos y ha definido la visión a 12 meses con KPIs concretos.",
    hacer: "Tiene la declaración de propósito, la ficha de modelo y la visión documentada con métricas.",
  },
  {
    number: 4,
    name: "Cliente ideal",
    month: 1,
    monthLabel: "Diagnóstico, autoconocimiento y claridad estratégica",
    hours: 8,
    theory: "El cliente ideal se descubre en los datos. Los 4 filtros. Punto A y punto Z del avatar. Limitaciones, obstáculos y objeciones.",
    mainExercise: "Filtrado conversacional de pacientes reales. Definición del punto A, Z, transformación, limitaciones, obstáculos y objeciones.",
    outputs: ["Matriz de filtrado de pacientes", "Informe completo del avatar", "Análisis del coste del paciente no ideal"],
    mentors: ["Jano Cabello"],
    knaasCompanion: "Conduce el filtrado, detecta patrones, hace preguntas de profundidad, construye el paso a paso de la transformación.",
    knaasGenerator: "Informe completo del avatar con punto A, Z, transformación, limitaciones, obstáculos, objeciones y citas literales.",
    saber: "Puede describir a su paciente ideal con suficiente precisión como para reconocerlo y explicar su punto A y Z.",
    decidir: "Ha identificado a quién va a dejar de captar activamente y por qué, con el coste calculado.",
    hacer: "Tiene la matriz de filtrado, el informe del avatar completo y el análisis del coste del paciente no ideal.",
  },
  {
    number: 5,
    name: "Propuesta de alto valor",
    month: 2,
    monthLabel: "Propuesta de valor y modelo de negocio",
    hours: 7,
    theory: "Diferencial vs genérico. 4 vectores de diferenciación. Ecuación del valor de Hormozi. Los 3 motores de crecimiento.",
    mainExercise: "Ecuación del valor aplicada a la clínica. Matriz de innovación. Carta de ventas de los programas.",
    outputs: ["Ecuación del valor de Hormozi aplicada", "Matriz de innovación completada", "Propuesta de valor en 3 formatos", "Carta de ventas de los programas", "Mapa de los 3 motores"],
    mentors: ["Jano Cabello"],
    knaasCompanion: "Guía la ecuación del valor, facilita la matriz de innovación, verifica coherencia con el avatar, diagnostica el motor más débil.",
    knaasAnalyst: "Blue Team sobre la propuesta — ¿es realmente diferencial o genérica con otro nombre?",
    knaasGenerator: "Propuesta de valor en 3 formatos, carta de ventas en el lenguaje del paciente ideal.",
    saber: "Puede explicar su diferencial en 20 segundos sin decir 'calidad' ni 'experiencia'.",
    decidir: "Ha priorizado las soluciones de la matriz y sabe qué motor es más débil y cómo reforzarlo.",
    hacer: "Tiene la propuesta en 3 formatos, la carta de ventas completa y el mapa de motores con diagnóstico.",
  },
  {
    number: 6,
    name: "Diseño de la oferta",
    month: 2,
    monthLabel: "Propuesta de valor y modelo de negocio",
    hours: 8,
    theory: "Del modelo sesión suelta al modelo programa. Arquitectura de alto valor. Viaje del cliente. Onboarding del paciente. 3 ofertas complementarias.",
    mainExercise: "Diseño de la metodología propia con viaje del cliente. Implementación de soluciones de la matriz del P5.",
    outputs: ["Plantilla de metodología propia", "Viaje del cliente documentado", "Plantillas de planificación y revisión", "Protocolo de onboarding del paciente", "Fichas de las 3 ofertas complementarias", "Plan de transición"],
    mentors: ["Alex Vallés"],
    knaasCompanion: "Verifica integración de soluciones del P5, que el viaje cubre puntos críticos y el onboarding genera valor temprano.",
    knaasGenerator: "Plantilla de metodología, viaje del cliente, protocolo de onboarding, plantillas de planificación, fichas de ofertas, comunicado de transición.",
    saber: "Puede explicar su metodología paso a paso y el viaje completo de su paciente ideal.",
    decidir: "Ha definido las 3 ofertas complementarias alineadas al motor más débil.",
    hacer: "Tiene los 6 outputs completos, listos para implementar con el primer paciente.",
  },
  {
    number: 7,
    name: "Pricing y rentabilidad",
    month: 2,
    monthLabel: "Propuesta de valor y modelo de negocio",
    hours: 7,
    theory: "Precio como expresión de valor. La trampa del bono con descuento. Primera sesión de alto valor. Upsell y downsell.",
    mainExercise: "Plantilla de fijación desde 3 vectores. Escalera de precios. Cálculo de impacto en margen con datos reales de PodiumMetrics.",
    outputs: ["Plantilla de fijación de precios", "Escalera de precios con upsell y downsell", "Calculadora de impacto en margen", "Estructura de pricing con argumentario", "Comunicado de subida de precios"],
    mentors: ["Jano Cabello"],
    knaasCompanion: "Calcula impacto con datos reales, detecta la trampa del bono, verifica que la escalera tiene downsell y upsell coherentes.",
    knaasAnalyst: "Pre-mortem de la nueva estructura de precios — ¿qué puede salir mal?",
    knaasGenerator: "Plantilla de fijación completada, escalera documentada, comunicado de subida adaptado.",
    saber: "Puede explicar su precio desde los 3 vectores (coste, valor, competencia) con argumentos sólidos.",
    decidir: "Ha fijado los precios de toda la escalera con argumentario completo.",
    hacer: "Tiene la estructura de pricing, la calculadora de impacto y el comunicado de subida listos.",
  },
  {
    number: 8,
    name: "Comunicación y marketing machine",
    month: 2,
    monthLabel: "Propuesta de valor y modelo de negocio",
    hours: 7,
    theory: "Identidad comunicativa. Marca personal vs corporativa. Canales basados en avatar. Marketing machine mínima. Web que convierte.",
    mainExercise: "Mensaje central y 2 canales prioritarios. Plan de comunicación en redes. Plan de contenido 4 semanas. Auditoría web.",
    outputs: ["Documento de identidad comunicativa", "Plan de comunicación en redes sociales", "Plan de contenido mínimo viable 4 semanas", "Checklist de auditoría web"],
    mentors: ["Jano Cabello", "Andrea de Cal Fregues"],
    knaasCompanion: "Verifica que canales responden al avatar, que la marca personal/corporativa tiene implicaciones en P14, métricas concretas.",
    knaasGenerator: "Identidad comunicativa, plan de comunicación, plan de contenido 4 semanas, checklist web, copy de secciones débiles.",
    saber: "Puede articular su mensaje central en 4 elementos y justificar sus 2 canales elegidos.",
    decidir: "Ha decidido la relación marca personal / corporativa y los canales con métricas de seguimiento.",
    hacer: "Tiene los 4 outputs completos y el plan de contenido listo para publicar la semana siguiente.",
  },
  {
    number: 9, name: "KPIs fundamentales", month: 3, monthLabel: "Control y sistemas mínimos", hours: 6,
    theory: "Los 5 KPIs esenciales. Qué mide cada uno. 3 errores de interpretación más frecuentes.",
    mainExercise: "Configuración del dashboard en PodiumMetrics con objetivos reales. 2 semanas de registro para hábito.",
    outputs: ["Dashboard de KPIs operativo", "Guía de interpretación de KPIs"],
    mentors: ["Alex Vallés"],
    knaasCompanion: "Detecta errores conceptuales en gastos, verifica coherencia KPIs-visión, explica interpretación.",
    saber: "Puede explicar qué decisión corresponde a cada desviación de cada KPI.", decidir: "Ha fijado objetivos a 3 meses para cada KPI con semáforo de alerta.", hacer: "Tiene el dashboard operativo y actualizado con los datos de las 2 primeras semanas.",
  },
  {
    number: 10, name: "Control financiero y rentabilidad real", month: 3, monthLabel: "Control y sistemas mínimos", hours: 8,
    theory: "Diferencia entre facturar y ganar. Estructura de costes. Sueldo del dueño como coste. Alquiler de mercado.",
    mainExercise: "Cálculo de rentabilidad real. Identificación de fugas. Guía de preguntas para el gestor.",
    outputs: ["Plantilla de rentabilidad real", "Fugas de margen con plan de acción", "Guía de preguntas para el gestor"],
    mentors: ["Javi Lázaro", "Alex Vallés"],
    knaasCompanion: "Detecta errores conceptuales prioritarios, verifica sueldo imputado y alquiler repercutido.",
    knaasGenerator: "Guía de preguntas para el gestor, identificación de fugas con plan de acción.",
    saber: "Conoce la diferencia entre su margen real y el que creía tener.", decidir: "Ha priorizado las fugas por impacto con fecha de corrección.", hacer: "Tiene la plantilla con números reales, las fugas identificadas y la guía del gestor.",
  },
  {
    number: 11, name: "Sistemas y protocolos mínimos", month: 3, monthLabel: "Control y sistemas mínimos", hours: 7,
    theory: "El dueño como cuello de botella. Framework frecuencia × impacto. Cómo escribir un protocolo ejecutable.",
    mainExercise: "Priorización de procesos a sistematizar. Diseño y documentación del protocolo prioritario.",
    outputs: ["Matriz de priorización de protocolos", "Protocolo completo prioritario"],
    mentors: ["Alex Vallés"],
    knaasCompanion: "Aplica framework frecuencia × impacto, verifica que el protocolo es ejecutable por otra persona.",
    knaasGenerator: "Borrador del protocolo prioritario en formato estándar.",
    saber: "Puede explicar el criterio de priorización y por qué eligió ese protocolo primero.", decidir: "Ha elegido el protocolo prioritario con criterio objetivo.", hacer: "Tiene el protocolo completo, probado en situación real.",
  },
  {
    number: 12, name: "Sistema mínimo de ventas", month: 3, monthLabel: "Control y sistemas mínimos", hours: 8,
    theory: "Venta como acto clínico. Historia natural de la lesión. Funnel infinito. Curva de motivación. NPS como generador de reseñas.",
    mainExercise: "Diseño del sistema de seguimiento completo. Plantilla detectora. Sistema NPS. Script de presentación.",
    outputs: ["Cuestionario de inicio", "Mapa curva de motivación", "Plantilla detectora de pérdidas", "Sistema NPS", "Protocolo de seguimiento", "Script de presentación", "Cuestionario de cierre"],
    mentors: ["Raúl Ferrer"],
    knaasCompanion: "Conduce el reencuadre de la promesa clínica, guía la plantilla detectora, verifica NPS en 3 momentos correctos.",
    knaasGenerator: "Todos los 7 outputs adaptados al avatar y patología predominante de la clínica.",
    saber: "Comprende la curva de motivación y puede identificar los 3 momentos de riesgo de abandono.", decidir: "Ha decidido los momentos de medición NPS y las señales de alerta de su plantilla detectora.", hacer: "Tiene los 7 outputs completos y listos para usar con el primer paciente.",
  },
  {
    number: 13, name: "Protocolo de equipo", month: 4, monthLabel: "Equipo, validación y transición", hours: 7,
    theory: "Selección por valores. Los 4 problemas de equipo. Onboarding como transmisor de propuesta. Por qué los fisios se van.",
    mainExercise: "Diagnóstico de problema de equipo actual. Perfil de contratación ideal. Protocolo de onboarding mínimo.",
    outputs: ["Perfil de contratación ideal", "Protocolo de onboarding mínimo", "Diagnóstico de equipo"],
    mentors: ["José Grau"],
    knaasCompanion: "Diagnostica si el problema es de selección, onboarding, formación o cultura. Verifica primera delegación.",
    knaasGenerator: "Perfil de contratación, protocolo de onboarding mínimo, script de comunicación.",
    saber: "Puede diagnosticar cuál de los 4 problemas de equipo tiene su clínica.", decidir: "Ha definido el perfil de contratación con valores y red flags.", hacer: "Tiene el protocolo de onboarding semana 1-4 y el perfil de contratación listos.",
  },
  {
    number: 14, name: "Sistemas de delegación", month: 4, monthLabel: "Equipo, validación y transición", hours: 7,
    theory: "Insustituible vs prescindible. Delegación progresiva en 4 fases. Transferencia de confianza. Marca de clínica.",
    mainExercise: "Mapa de tareas delegables. Plan de delegación progresiva. Primera delegación ejecutada.",
    outputs: ["Mapa de tareas delegables vs no delegables", "Plan de delegación progresiva", "Script de comunicación de cambio de fisio"],
    mentors: ["Jano Cabello"],
    knaasCompanion: "Cruza mapa de liderazgo P2 con necesidades del modelo objetivo P3. Verifica delegación con fecha y persona.",
    saber: "Puede explicar las 4 fases de delegación y dónde está en cada tarea.", decidir: "Ha decidido qué delega primero, a quién, y cuándo.", hacer: "Ha ejecutado la primera delegación real y la tiene documentada.",
  },
  {
    number: 15, name: "Validación Lean", month: 4, monthLabel: "Equipo, validación y transición", hours: 8,
    theory: "Mentalidad Lean aplicada a clínica. Vertical mínima. Documentar para aprender. Caso de éxito como activo.",
    mainExercise: "Elección de vertical mínima. Implementación real con 3+ pacientes. Registro. Caso de éxito documentado.",
    outputs: ["Registro de validación", "Caso de éxito documentado", "Plan de ajuste post-validación"],
    mentors: ["Alex Vallés"],
    knaasCompanion: "Seguimiento activo de las 3+ implementaciones, detección de patrones de fricción, ajuste antes de escalar.",
    knaasAnalyst: "Devil's Advocate sobre resultados de validación — ¿estamos interpretando bien los datos?",
    knaasGenerator: "Caso de éxito documentado en formato narrativo listo para prueba social.",
    saber: "Puede explicar qué ha aprendido de la validación y qué ajustaría.", decidir: "Ha decidido qué ajustes hace antes de escalar.", hacer: "Tiene el registro completo, el caso de éxito y el plan de ajuste.",
  },
  {
    number: 16, name: "Diagnóstico de siguiente escalón", month: 4, monthLabel: "Equipo, validación y transición", hours: 6,
    theory: "Evaluar consolidación real vs percepción. Diferencia entre saber y haber implementado. Qué significa estar listo para OPTIMIZA.",
    mainExercise: "Evaluación de consolidación de 15 pasos. Comparativa numérica P1 vs actual. Decisión sobre siguiente paso.",
    outputs: ["Informe de consolidación ACTIVA", "Plan de siguiente paso"],
    mentors: ["Alex Vallés"],
    knaasCompanion: "Genera comparativa numérica y de madurez automática cruzando P1 con situación actual.",
    knaasGenerator: "Informe de consolidación completo con comparativa cuanti + cuali, plan de siguiente paso hacia OPTIMIZA.",
    saber: "Puede evaluar el estado de consolidación de cada paso con evidencia.", decidir: "Ha decidido si va a OPTIMIZA o consolida, con argumentos y plan.", hacer: "Tiene el informe de consolidación completo y el plan de siguiente paso con fechas.",
  },
];
