export interface StepDefinition {
  number: number;
  name: string;
  month: number;
  monthLabel: string;
  hours: number;
  theory: string;
  mainExercise: string;
  outputs: string[];
  mentors: string[];
  knaasCompanion: string;
  knaasAnalyst?: string;
  knaasGenerator?: string;
  saber: string;
  decidir: string;
  hacer: string;
}

export const ACTIVA_STEPS: StepDefinition[] = [
  // ── MES 1: Diagnóstico, autoconocimiento y claridad estratégica (Pasos 0–4) ──
  {
    number: 0,
    name: "Construyendo tu criterio estratégico",
    month: 1,
    monthLabel: "Diagnóstico, autoconocimiento y claridad estratégica",
    hours: 4,
    theory: "El salto de identidad: de técnico a dueño. Creencias limitantes del fisioterapeuta. El coste de no cambiar. Responsabilidad total. El compromiso con el proceso.",
    mainExercise: "Reflexión guiada sobre tu situación actual como dueño, tus miedos, tus excusas y lo que estás dispuesto a cambiar. Carta de compromiso contigo mismo.",
    outputs: ["Autoevaluación de mentalidad empresarial", "Carta de compromiso personal"],
    mentors: ["Alex Vallés"],
    knaasCompanion: "Guía la reflexión profunda sobre la identidad fisio vs empresario, detecta creencias limitantes y ayuda a formular el compromiso personal con el programa.",
    saber: "Comprende la diferencia entre ser técnico y ser empresario, y puede identificar sus propias creencias limitantes.",
    decidir: "Ha decidido comprometerse con el cambio de mentalidad y ha identificado qué está dispuesto a hacer diferente.",
    hacer: "Tiene la autoevaluación completada y la carta de compromiso redactada en sus propias palabras.",
  },
  {
    number: 1,
    name: "Diagnóstico y control de tu negocio actual",
    month: 1,
    monthLabel: "Diagnóstico, autoconocimiento y claridad estratégica",
    hours: 6,
    theory: "Qué KPIs importan y por qué. Los 6 errores conceptuales. Las 7 áreas de madurez empresarial. Sistema de control básico.",
    mainExercise: "Test de madurez empresarial conversacional + volcado de datos en la plataforma con detección de errores en tiempo real.",
    outputs: ["Mapa de madurez empresarial", "Informe diagnóstico 360° cuantitativo y cualitativo", "Tabla de KPIs de partida"],
    mentors: ["Alex Vallés"],
    knaasCompanion: "Conduce el test de madurez en 7 áreas, guía el volcado de datos, detecta los 6 errores conceptuales, genera el informe 360° y guarda el snapshot protegido.",
    saber: "Comprende qué mide cada KPI y puede explicar los 6 errores conceptuales aplicados a su clínica.",
    decidir: "Ha identificado los 3 puntos más débiles de su clínica y las prioridades de trabajo del programa.",
    hacer: "Tiene el informe 360° completo (cuanti + cuali) y la tabla de KPIs de partida.",
  },
  {
    number: 2,
    name: "Cómo montar un negocio que vaya contigo y que sepas liderar",
    month: 1,
    monthLabel: "Diagnóstico, autoconocimiento y claridad estratégica",
    hours: 8,
    theory: "Los 4 modelos de clínica. Ciclo del negocio. Cambio de identidad fisio→empresario. 6 estilos de liderazgo Goleman. Motores vs frenos. El Pacto de Ulises.",
    mainExercise: "Identificación del modelo actual y objetivo. Definición personal de éxito con métricas y fechas. Autoevaluación de estilos de liderazgo. Plan de desarrollo como líder.",
    outputs: ["Perfil empresarial personal", "Mapa de liderazgo personal", "Plan de desarrollo como líder y dueño", "Pacto de Ulises"],
    mentors: ["Alex Vallés"],
    knaasCompanion: "Conduce el análisis en profundidad de motores y frenos, construye el plan de desarrollo con objetivos y fechas, ayuda a formular el Pacto de Ulises.",
    knaasAnalyst: "Devil's Advocate sobre creencias limitantes — ¿son realmente creencias o restricciones reales del mercado?",
    saber: "Puede articular su definición de éxito con números y fecha, y nombrar sus 3 frenos principales con su impacto concreto.",
    decidir: "Ha decidido los 3 comportamientos de liderazgo que trabajará durante el programa con acciones específicas.",
    hacer: "Tiene el perfil empresarial, el mapa de liderazgo, el plan de desarrollo y el Pacto de Ulises redactado en sus palabras.",
  },
  {
    number: 3,
    name: "Lo que hace crecer a un buen negocio de fisioterapia (y lo que debes evitar)",
    month: 1,
    monthLabel: "Diagnóstico, autoconocimiento y claridad estratégica",
    hours: 7,
    theory: "Los motores de crecimiento de una clínica fisioreferente. Las palancas que impulsan captación y beneficios reales. Competitividad en fisioterapia. Propósito como criterio de decisión.",
    mainExercise: "Identificación de los motores de crecimiento aplicados a tu clínica. Ejercicio del puzzle del propósito. Construcción de la visión con KPIs concretos.",
    outputs: ["Declaración de propósito", "Ficha de modelo y fase de ciclo", "Documento de visión con KPIs objetivo"],
    mentors: ["Alex Vallés"],
    knaasCompanion: "Identifica modelo y fase del ciclo a partir de los datos del P1. Guía el ejercicio del propósito.",
    knaasGenerator: "Borrador de la declaración de propósito y el documento de visión con KPIs objetivo.",
    saber: "Puede explicar su modelo actual, el objetivo, y por qué ese modelo es coherente con su diagnóstico.",
    decidir: "Ha elegido modelo objetivo con argumentos y ha definido la visión a 12 meses con KPIs concretos.",
    hacer: "Tiene la declaración de propósito, la ficha de modelo y la visión documentada con métricas.",
  },
  {
    number: 4,
    name: "Conoce quién es tu cliente ideal (y quién no)",
    month: 1,
    monthLabel: "Diagnóstico, autoconocimiento y claridad estratégica",
    hours: 8,
    theory: "El cliente ideal se descubre en los datos. Los 4 filtros. Punto A y punto Z del avatar. Limitaciones, obstáculos y objeciones.",
    mainExercise: "Filtrado conversacional de pacientes reales. Definición del punto A, Z, transformación, limitaciones, obstáculos y objeciones.",
    outputs: ["Matriz de filtrado de pacientes", "Informe completo del avatar", "Análisis del coste del paciente no ideal"],
    mentors: ["Jano Cabello"],
    knaasCompanion: "Conduce el filtrado, detecta patrones, hace preguntas de profundidad, construye el paso a paso de la transformación.",
    knaasGenerator: "Informe completo del avatar con punto A, Z, transformación, limitaciones, obstáculos, objeciones y citas literales.",
    saber: "Puede describir a su paciente ideal con suficiente precisión como para reconocerlo y explicar su punto A y Z.",
    decidir: "Ha identificado a quién va a dejar de captar activamente y por qué, con el coste calculado.",
    hacer: "Tiene la matriz de filtrado, el informe del avatar completo y el análisis del coste del paciente no ideal.",
  },

  // ── MES 2: Propuesta de valor y modelo de negocio (Pasos 5–8) ──
  {
    number: 5,
    name: "Define el problema de tu avatar con claridad",
    month: 2,
    monthLabel: "Propuesta de valor y modelo de negocio",
    hours: 7,
    theory: "Tus pacientes no compran una lesión. Compran recuperar su estatus y su vida. El primer pain es higiénico. Lo que te hace elegible es más profundo. Diferencial vs genérico.",
    mainExercise: "Definición precisa del problema real del avatar. Ecuación del valor aplicada. Propuesta de valor en 3 formatos.",
    outputs: ["Definición del problema real del avatar", "Ecuación del valor aplicada", "Propuesta de valor en 3 formatos"],
    mentors: ["Jano Cabello"],
    knaasCompanion: "Guía la ecuación del valor, facilita la definición profunda del problema, verifica coherencia con el avatar.",
    knaasAnalyst: "Blue Team sobre la propuesta — ¿es realmente diferencial o genérica con otro nombre?",
    knaasGenerator: "Propuesta de valor en 3 formatos, definición del problema en el lenguaje del paciente ideal.",
    saber: "Puede explicar el problema real de su paciente sin reducirlo a 'recuperarse de una lesión'.",
    decidir: "Ha priorizado las soluciones de la matriz y sabe qué motor es más débil y cómo reforzarlo.",
    hacer: "Tiene la propuesta en 3 formatos y la definición del problema documentada.",
  },
  {
    number: 6,
    name: "Creando un servicio de fisioterapia de alto valor",
    month: 2,
    monthLabel: "Propuesta de valor y modelo de negocio",
    hours: 8,
    theory: "Del modelo sesión suelta al modelo programa. Arquitectura de alto valor. Viaje del cliente. Onboarding del paciente. La solución la da el sistema, no solo un fisio genial.",
    mainExercise: "Diseño de la metodología propia con viaje del cliente. Protocolo de onboarding. Ofertas complementarias.",
    outputs: ["Plantilla de metodología propia", "Viaje del cliente documentado", "Protocolo de onboarding del paciente", "Fichas de ofertas complementarias", "Plan de transición"],
    mentors: ["Alex Vallés"],
    knaasCompanion: "Verifica que el servicio está centrado en valor percibido por el paciente y no solo en la técnica del fisio.",
    knaasGenerator: "Plantilla de metodología, viaje del cliente, protocolo de onboarding, fichas de ofertas.",
    saber: "Puede explicar su metodología paso a paso y el viaje completo de su paciente ideal.",
    decidir: "Ha definido las ofertas complementarias alineadas al motor más débil.",
    hacer: "Tiene los outputs completos, listos para implementar con el primer paciente.",
  },
  {
    number: 7,
    name: "Construyendo un sistema de alta fidelización",
    month: 2,
    monthLabel: "Propuesta de valor y modelo de negocio",
    hours: 7,
    theory: "Sistema de seguimiento FR. Fidelizar clientes para ingresos recurrentes. Curva de motivación del paciente. NPS como generador de reseñas.",
    mainExercise: "Diseño del sistema de seguimiento completo. Plantilla detectora de pérdidas. Sistema NPS. Protocolo de seguimiento.",
    outputs: ["Protocolo de seguimiento", "Plantilla detectora de pérdidas", "Sistema NPS", "Mapa curva de motivación"],
    mentors: ["Alex Vallés"],
    knaasCompanion: "Conduce el diseño del sistema de seguimiento, guía la plantilla detectora, verifica NPS en los momentos correctos.",
    knaasGenerator: "Protocolo de seguimiento y plantilla detectora adaptados al avatar y patología predominante.",
    saber: "Comprende la curva de motivación y puede identificar los 3 momentos de riesgo de abandono.",
    decidir: "Ha decidido los momentos de medición NPS y las señales de alerta de su plantilla detectora.",
    hacer: "Tiene el protocolo de seguimiento completo y el sistema NPS listos.",
  },
  {
    number: 8,
    name: "Organiza la oferta de servicios y pon precios adecuados",
    month: 2,
    monthLabel: "Propuesta de valor y modelo de negocio",
    hours: 7,
    theory: "Precio como expresión de valor. La trampa del bono con descuento. Escalera de precios. Upsell y downsell. Cómo comunicar subidas de precios sin riesgo.",
    mainExercise: "Plantilla de fijación desde 3 vectores. Escalera de precios. Cálculo de impacto en margen con datos reales.",
    outputs: ["Plantilla de fijación de precios", "Escalera de precios con upsell y downsell", "Calculadora de impacto en margen", "Comunicado de subida de precios"],
    mentors: ["Jano Cabello"],
    knaasCompanion: "Calcula impacto con datos reales, detecta la trampa del bono, verifica que la escalera es coherente.",
    knaasAnalyst: "Pre-mortem de la nueva estructura de precios — ¿qué puede salir mal?",
    knaasGenerator: "Plantilla de fijación completada, escalera documentada, comunicado de subida adaptado.",
    saber: "Puede explicar su precio desde los 3 vectores (coste, valor, competencia) con argumentos sólidos.",
    decidir: "Ha fijado los precios de toda la escalera con argumentario completo.",
    hacer: "Tiene la estructura de pricing, la calculadora de impacto y el comunicado de subida listos.",
  },

  // ── MES 3: Captación, ventas y marca personal (Pasos 9–12) ──
  {
    number: 9,
    name: "Impulsa tus ventas basándote en la evidencia",
    month: 3,
    monthLabel: "Captación, ventas y marca personal",
    hours: 7,
    theory: "Venta como acto clínico. En FisioReferentes nunca prometemos algo que la evidencia diga que es imposible cumplir. El sistema de ventas infinito que cuida de tu paciente más allá de su lesión.",
    mainExercise: "Diseño del sistema de ventas basado en evidencia. Script de presentación. Cuestionarios de inicio y cierre.",
    outputs: ["Script de presentación de servicios", "Cuestionario de inicio", "Cuestionario de cierre", "Sistema de ventas basado en evidencia"],
    mentors: ["Alex Vallés"],
    knaasCompanion: "Conduce el reencuadre de la promesa clínica, verifica que las ventas están alineadas con la evidencia.",
    knaasGenerator: "Script de presentación y cuestionarios adaptados al avatar y patología predominante.",
    saber: "Comprende que vender es ayudar al paciente a tomar la decisión más adecuada.",
    decidir: "Ha definido el sistema de ventas con argumentos basados en evidencia.",
    hacer: "Tiene el script, los cuestionarios y el sistema completo listos para usar.",
  },
  {
    number: 10,
    name: "Cómo comunicar para atraer a los buenos clientes, en el momento adecuado",
    month: 3,
    monthLabel: "Captación, ventas y marca personal",
    hours: 7,
    theory: "Comunicación y marketing son mucho más que redes sociales. El mensaje que quieres trasladar. Coherencia en todos los canales. Reputación digital y offline.",
    mainExercise: "Mensaje central y canales prioritarios. Plan de comunicación. Plan de contenido mínimo viable 4 semanas.",
    outputs: ["Documento de identidad comunicativa", "Plan de comunicación en canales", "Plan de contenido mínimo viable 4 semanas"],
    mentors: ["Jano Cabello"],
    knaasCompanion: "Verifica que canales responden al avatar y que el mensaje es coherente en todos los puntos de contacto.",
    knaasGenerator: "Identidad comunicativa, plan de comunicación, plan de contenido 4 semanas.",
    saber: "Puede articular su mensaje central y justificar sus canales elegidos.",
    decidir: "Ha decidido los canales con métricas de seguimiento.",
    hacer: "Tiene los outputs completos y el plan de contenido listo para publicar.",
  },
  {
    number: 11,
    name: "Conviértete en un Fisioreferente con tu marca personal",
    month: 3,
    monthLabel: "Captación, ventas y marca personal",
    hours: 7,
    theory: "Tu marca personal no es solo un imán para pacientes, sino también para socios clave y equipo de talento. Marca personal vs corporativa. Posicionarte como referente en tu nicho.",
    mainExercise: "Construcción de marca personal que impulse tu marca comercial y tu clínica. Estrategia de posicionamiento.",
    outputs: ["Estrategia de marca personal", "Plan de posicionamiento como referente", "Integración marca personal-comercial"],
    mentors: ["Jano Cabello"],
    knaasCompanion: "Guía la construcción de marca personal coherente con el modelo de clínica elegido.",
    knaasGenerator: "Estrategia de marca personal documentada y plan de posicionamiento.",
    saber: "Entiende que la marca personal atrae pacientes, socios y talento.",
    decidir: "Ha definido la relación marca personal / corporativa con estrategia clara.",
    hacer: "Tiene la estrategia de marca personal documentada y el plan de posicionamiento.",
  },
  {
    number: 12,
    name: "Tus primeros sistemas. Equipo y orden",
    month: 3,
    monthLabel: "Captación, ventas y marca personal",
    hours: 8,
    theory: "El dueño como cuello de botella. Delegación progresiva. Selección por valores. Los 4 problemas de equipo. Onboarding como transmisor de propuesta. Sistemas que estandaricen el valor.",
    mainExercise: "Protocolo de equipo mínimo. Perfil de contratación ideal. Mapa de tareas delegables. Plan de delegación progresiva.",
    outputs: ["Perfil de contratación ideal", "Protocolo de onboarding mínimo", "Mapa de tareas delegables", "Plan de delegación progresiva"],
    mentors: ["Alex Vallés"],
    knaasCompanion: "Diagnostica si el problema es de selección, onboarding, formación o cultura. Aplica framework frecuencia × impacto.",
    knaasGenerator: "Perfil de contratación, protocolo de onboarding, plan de delegación.",
    saber: "Puede diagnosticar cuál de los 4 problemas de equipo tiene su clínica y entiende cómo delegar.",
    decidir: "Ha definido el perfil de contratación con valores y red flags, y qué delega primero.",
    hacer: "Tiene el protocolo de onboarding, el perfil de contratación y el plan de delegación listos.",
  },

  // ── MES 4: Graduación y transición (Paso 13) ──
  {
    number: 13,
    name: "La graduación ACTIVA — Los sistemas vitales para tu nuevo negocio",
    month: 4,
    monthLabel: "Graduación y transición",
    hours: 6,
    theory: "Descubre los sistemas vitales para que tu negocio crezca sin caos. Evaluar consolidación real vs percepción. Qué significa estar listo para OPTIMIZA.",
    mainExercise: "Evaluación de consolidación de los 13 pasos. Comparativa numérica P1 vs actual. Decisión sobre siguiente paso.",
    outputs: ["Informe de consolidación ACTIVA", "Plan de siguiente paso hacia OPTIMIZA"],
    mentors: ["Alex Vallés"],
    knaasCompanion: "Genera comparativa numérica y de madurez automática cruzando P1 con situación actual.",
    knaasGenerator: "Informe de consolidación completo con comparativa cuanti + cuali, plan de siguiente paso hacia OPTIMIZA.",
    saber: "Puede evaluar el estado de consolidación de cada paso con evidencia.",
    decidir: "Ha decidido si va a OPTIMIZA o consolida, con argumentos y plan.",
    hacer: "Tiene el informe de consolidación completo y el plan de siguiente paso con fechas.",
  },
];
